version: '3.8'

services:
  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
  
